-- این اسکریپت دیتابیس شما را تعمیر می‌کند.
-- توجه: تمام اطلاعات قبلی پاک خواهد شد و جدول از نو ساخته می‌شود.

-- 1. حذف جدول قدیمی (اگر وجود داشته باشد)
drop table if exists todos;

-- 2. ساخت مجدد جدول با ستون‌های صحیح
create table todos (
  id bigint generated by default as identity primary key,
  task text not null,          -- این ستون برای متن کار ضروری است
  is_complete boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. تنظیمات امنیت (RLS)
alter table todos enable row level security;

-- 4. ایجاد دسترسی عمومی مجدد
create policy "Public Access"
on todos
for all
to anon
using (true)
with check (true);

-- 5. تست: افزودن یک آیتم آزمایشی
insert into todos (task) values ('تست اولیه سیستم');
