-- 1. این کد را کپی کنید.
-- 2. به داشبورد Supabase بروید.
-- 3. وارد بخش SQL Editor شوید (آیکون دوم از پایین در منوی سمت چپ).
-- 4. روی "New Query" کلیک کنید.
-- 5. این کد را در آنجا پیست کنید و دکمه "Run" را بزنید.

-- ساخت جدول تودو
create table todos (
  id bigint generated by default as identity primary key,
  task text not null,
  is_complete boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- فعال‌سازی امنیت سطح ردیف (RLS) - این استاندارد Supabase است
alter table todos enable row level security;

-- ایجاد دسترسی عمومی (چون سیستم لاگین نخواستید، همه دسترسی دارند)
create policy "Public Access"
on todos
for all
to anon  -- دسترسی برای کاربران ناشناس
using (true)
with check (true);
